// ============================================================================
// LD7 elementų numerių registras. Bankas LD7-64-A-2026.
// REGISTRY-CODES: T01:T10 B01:B17 E01:E06 A03.01 A03.02 A04.01:A04.05 A05.01 A05.02 A06.01:A06.03 V02 H01
// ============================================================================

function ids = ld7_terminal_ids()
    ids = ["E_P";"E_N";"K1";"K2";"A_P";"A_N";"R_A";"R_B";"V_P";"V_N"];
endfunction

function code = ld7_terminal_code(id)
    tids = ld7_terminal_ids();
    k = find(tids == id);
    if size(k, "*") ~= 1 then code = ""; else code = msprintf("T%02d", k(1)); end
endfunction

function name = ld7_terminal_name(id)
    names = ["Šaltinio E + gnybtas";"Šaltinio E − gnybtas"; ...
             "Jungiklio įėjimas";"Jungiklio išėjimas";"Ampermetro + gnybtas"; ...
             "Ampermetro − gnybtas";"Reostato R gnybtas a";"Reostato R gnybtas b"; ...
             "Voltmetro + zondas";"Voltmetro − zondas"];
    tids = ld7_terminal_ids();
    k = find(tids == id);
    if size(k, "*") ~= 1 then name = id; else name = names(k(1)); end
endfunction

function [ids, callbacks, labels, hints] = ld7_button_registry()
    ids = ["B01";"B02";"B03";"B04";"B05";"B06";"B07";"B08";"B09"; ...
           "B10";"B11";"B12";"B13";"B14";"B15";"B16";"B17"];
    callbacks = ["ld7_toggle_power()";"ld7_toggle_switch()";"ld7_measure()"; ...
                 "ld7_show_wiring_guide()";"ld7_show_stand_map()";"ld7_restore_stage()"; ...
                 "ld7_toggle_solution()";"bench_export_current(""LD7"")";"ld7_restart()"; ...
                 "ld7_set_mode(1)";"ld7_set_mode(2)";"ld7_set_mode(3)"; ...
                 "ld7_set_position(1)";"ld7_set_position(2)";"ld7_set_position(3)"; ...
                 "ld7_set_position(4)";"ld7_set_position(5)"];
    labels = ["MAITINIMAS";"JUNGIKLIS";"MATUOTI";"KAIP SUJUNGTI";"STENDO ŽEMĖLAPIS"; ...
              "ATKURTI";"PAVYZDYS";"ATASKAITA";"IŠ NAUJO"; ...
              "DARBINĖ";"TUŠČIOJI EIGA";"VIRTUALUS TJ"; ...
              "PADĖTIS 1";"PADĖTIS 2";"PADĖTIS 3";"PADĖTIS 4";"PADĖTIS 5"];
    hints = ["Įjungti/išjungti šaltinį.";"Atidaryti/uždaryti jungiklį."; ...
             "Užfiksuoti U ir I į žurnalą."; ...
             "Parodyti sujungimo seką."; ...
             "Numerių paskirtis."; ...
             "Atkurti stendą."; ...
             "Teisingas sujungimas."; ...
             "HTML ataskaita."; ...
             "Pradėti iš naujo."; ...
             "Darbo grandinė: E → K → A → R, voltmetras prie R."; ...
             "Voltmetras prie šaltinio galų; srovės nėra."; ...
             "Virtualus kontroliuojamas TJ modelis; realiame stende tik pagal dėstytojo procedūrą."; ...
             "Mažiausia reostato varža pagal variantą."; ...
             "Reostato varža pagal variantą."; ...
             "Reostato varža pagal variantą."; ...
             "Reostato varža pagal variantą."; ...
             "Didžiausia reostato varža pagal variantą."];
endfunction

function [code, label, hint] = ld7_button_info(cb)
    [ids, callbacks, labels, hints] = ld7_button_registry();
    k = find(callbacks == cb);
    if size(k, "*") ~= 1 then error("Valdiklis ne LD7 registre: " + cb); end
    code = ids(k(1)); label = labels(k(1)); hint = hints(k(1));
endfunction

function code = ld7_stage_code(n)
    code = msprintf("E%02d", n);
endfunction

function code = ld7_answer_code(n, k)
    code = msprintf("A%02d.%02d", n, k);
endfunction

function codes = ld7_all_codes()
    tids = ld7_terminal_ids();
    codes = emptystr(size(tids, "*"), 1);
    for k = 1:size(tids, "*"); codes(k) = msprintf("T%02d", k); end
    [bids, callbacks, labels, hints] = ld7_button_registry();
    codes = [codes; bids];
    for n = 1:6; codes($+1, 1) = msprintf("E%02d", n); end
    codes = [codes; "A03.01";"A03.02";"A04.01";"A04.02";"A04.03";"A04.04";"A04.05"; ...
             "A05.01";"A05.02";"A06.01";"A06.02";"A06.03"];
    codes = [codes; "V02";"H01"];
endfunction
