// LD2 konfigūracija. Visos varžos - omais, talpos - faradais,
// induktyvumai - henriais, įtampos - V RMS, dažniai - Hz.

function cfg = ld2_default_config()
    cfg = struct( ...
        "E_RC",       9.0, ...
        "F_RC",      60.0, ...
        "R8",      1000.0, ...
        "C2",         4.7e-6, ...
        "E_RL",       9.0, ...
        "F_RL",      50.0, ...
        "R9",      1000.0, ...
        "L1",         0.5, ...
        "E_RLC",      5.0, ...
        "R13",      100.0, ...
        "L3",         0.100, ...
        "C4",        10.0e-9, ...
        "F_MIN",      0.0, ...
        "F_MAX",  10000.0, ...
        "F_INIT",  5000.0, ...
        "ANSWER_TOL_REL", 0.015, ...
        "ANSWER_TOL_ABS", 0.005);
endfunction

function s = ld2_initial_state(cfg)
    s = struct( ...
        "step", 1, ...
        "completed", zeros(1, 12), ...
        "skipped", zeros(1, 12), ...
        "teacher_mode", %f, ...
         "power", %f, ...
        "amp_live", %nan, ...
        "volt_live", %nan, ...
        "volt_live_target", "", ...
        "selected_terminal", "", ...
        "rc_connections", emptystr(0, 2), ...
        "rl_connections", emptystr(0, 2), ...
        "rlc_connections", emptystr(0, 2), ...
        "rc_voltage_target", "", ...
        "rl_voltage_target", "", ...
        "rlc_voltage_target", "", ...
        "rc_I", %nan, ...
        "rc_UR", %nan, ...
        "rc_UC", %nan, ...
        "rc_UE", %nan, ...
        "rl_I", %nan, ...
        "rl_UR", %nan, ...
        "rl_UL", %nan, ...
        "rl_UE", %nan, ...
        "rlc_I", %nan, ...
        "rlc_UR", %nan, ...
        "rlc_UL", %nan, ...
        "rlc_UC", %nan, ...
        "rlc_ULC", %nan, ...
        "freq", cfg.F_INIT, ...
        "res_f", [], ...
        "res_ur", [], ...
        "res_i", [], ...
        "res_fr_meas", %nan, ...
        "f1_meas", %nan, ...
        "f2_meas", %nan, ...
        "sweep_f", [], ...
        "sweep_ur", [], ...
        "answers", %nan * ones(12, 8), ...
        "choices", zeros(12, 2), ...
        "last_error", "", ...
        "last_fix", "");
    s.assessment=%f;
    s.practice_used=%f;
    s.answers_text = emptystr(12,8);
    s.revision = 0;
    s.measurements = list();
    s.last_voltage = ld2_empty_reading();
    s.last_current = ld2_empty_reading();
    s.peak_f = [];
    s.peak_u = [];
    s.peak_target = emptystr(0,1);
    s.f1_u = %nan;
    s.f2_u = %nan;
    s.sweep_source = emptystr(0,1);
    s.free_note = "";
    s.student = student_empty("LD2");
endfunction

function ld2_reset_state()
    global LD2;
    teacher = LD2.state.teacher_mode;
    student = LD2.state.student;
    LD2.state = ld2_initial_state(LD2.cfg);
    LD2.state.teacher_mode = teacher;
    LD2.state.student = student;
endfunction

function [ok,why]=ld2_validate_config(cfg)
    ok=%f; why="";
    names=["E_RC" "F_RC" "R8" "C2" "E_RL" "F_RL" "R9" "L1" "E_RLC" "R13" "L3" "C4"];
    for name=names
        if ~isfield(cfg,name) then why="Trūksta parametro "+name+"."; return; end
        v=ld2_config_value(cfg,name);
        if type(v)<>1 then why=name+" turi būti realus skaičius."; return; end
        if size(v,"*")<>1 then why=name+" turi būti vienas skaičius."; return; end
        if ~isreal(v) then why=name+" negali būti kompleksinis."; return; end
        if isnan(v) | isinf(v) | v<=0 then why=name+" turi būti baigtinis ir teigiamas."; return; end
    end
    rc=ld2_rc_values(cfg.E_RC,cfg.F_RC,cfg.R8,cfg.C2);
    rl=ld2_rl_values(cfg.E_RL,cfg.F_RL,cfg.R9,cfg.L1);
    vals=[rc.X rc.Z rc.I rc.UR rc.UX rc.P rl.X rl.Z rl.I rl.UR rl.UX rl.P];
    if or(isnan(vals)) | or(isinf(vals)) then
        why="RC arba RL parametrai per dideli ar per maži baigtiniam skaičiavimui."; return;
    end
    rr=ld2_peak_reference(cfg);
    if isnan(rr.FL) | isnan(rr.FC) then
        why="Šiam darbui reikia UL ir UC maksimumų. Pasirinkite Q > 1/sqrt(2), t. y. R13 < sqrt(2*L3/C4)."; return;
    end
    if rr.F1<1 | rr.F2>cfg.F_MAX | rr.FC-rr.BW/2<1 | rr.FL+rr.BW/2>cfg.F_MAX then
        why="Rezonanso, -3 dB ir maksimumų paieškos dažniai netelpa 1–10000 Hz diapazone. Pakeiskite R13, L3 arba C4."; return;
    end
    if isinf(rr.F0) | isnan(rr.F0) | rr.BW<=0 then why="Parametrai per dideli arba per maži skaičiavimui."; return; end
    ok=%t;
endfunction

function v=ld2_config_value(cfg,name)
    select name
    case "E_RC" then v=cfg.E_RC;
    case "F_RC" then v=cfg.F_RC;
    case "R8" then v=cfg.R8;
    case "C2" then v=cfg.C2;
    case "E_RL" then v=cfg.E_RL;
    case "F_RL" then v=cfg.F_RL;
    case "R9" then v=cfg.R9;
    case "L1" then v=cfg.L1;
    case "E_RLC" then v=cfg.E_RLC;
    case "R13" then v=cfg.R13;
    case "L3" then v=cfg.L3;
    case "C4" then v=cfg.C4;
    case "F_MIN" then v=cfg.F_MIN;
    case "F_MAX" then v=cfg.F_MAX;
    case "F_INIT" then v=cfg.F_INIT;
    case "ANSWER_TOL_REL" then v=cfg.ANSWER_TOL_REL;
    case "ANSWER_TOL_ABS" then v=cfg.ANSWER_TOL_ABS;
    else error("Nežinomas LD2 parametras: "+name);
    end
endfunction
